### ISSUE TITLE
Sender Send button not doing anything

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [jmcker/Peer-to-Peer-Cue-System#6] opened 2018-12-19 04:40 UTC
after making successful connect, On sender.html send button is not working. Even i try to log the event s`endButton.onclick` but no log is showing.

**Comment by jmcker** [comment] 2018-12-20 03:26
Is this still reproducible? If so, which browser are you using?

I think there were some issues with the PeerJS servers the other day, but it appears to have been resolved now.

**Comment by jmcker** [comment] 2019-02-02 00:06
Closing since I can't reproduce without a bit more info. Feel free to reopen if it's still an issue.

**Closed as completed by jmcker** 2019-02-02 00:06 UTC
